[package]
name = "h_closures_threads"
version = "2.3.4"
authors = ["Fabiana Liria <fabiliria@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
